targets:
  freezed:
    builders:
      freezed:freezed:
        enabled: true
  $default:
    dependencies:
      - dart_mappable_example_freezed:freezed
    builders:
      freezed:freezed:
        enabled: false
      dart_mappable:
        generate_for:
          - lib/main.dart
