name: dart_mappable_example_freezed

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  dart_mappable: ^2.0.0-dev.2
  freezed_annotation: ^2.2.0

dev_dependencies:
  build_runner: ^2.2.0
  dart_mappable_builder: ^2.0.0-dev.2
  freezed: ^2.2.0
  lints: ^2.0.1

dependency_overrides:
  dart_mappable:
    path: ../../packages/dart_mappable
  dart_mappable_builder:
    path: ../../packages/dart_mappable_builder