name: dart_mappable_example_freezed

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dart_mappable:
    path: ../../
  freezed_annotation: ^1.1.0

dev_dependencies:
  build_runner: ^2.1.0
  freezed: ^1.1.0
  lints: ^1.0.1