builders:
  dart_mappable:
    import: "package:dart_mappable/builder.dart"
    builder_factories: [ "buildMappable" ]
    build_extensions: { ".dart": [ ".mapper.g.dart" ] }
    auto_apply: none
    build_to: source
targets:
  $default:
    builders:
      dart_mappable:
        generate_for:
          - test/test.dart
        options:
          caseStyle: snakeCase
          enumCaseStyle: camelCase
          libraries:
            lib/annotations.dart:
              include: []
            lib/src/flags.dart:
              include: []
            test/models/model.dart:
              exclude: [PlayerHooks]
