builders:
  dart_mappable:
    import: "package:dart_mappable/builder.dart"
    builder_factories: [ "buildMappable" ]
    build_extensions: { ".dart": [ ".mapper.g.dart" ] }
    auto_apply: root_package
    build_to: source