name: dart_mappable

packages:
  - packages/**
  - examples/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  test:
    run: melos exec -- 'dart test'
    select-package:
      scope: dart_mappable
  build:
    run: melos exec -- 'dart run build_runner build --delete-conflicting-outputs'
  analyze:
    run: melos exec -- 'dart analyze .'