name: dart_mappable
description: Serialize / deserialize dart objects effortlessly, without any boilerplate code or compromises.
version: 1.0.0-dev.1
repository: https://github.com/schultek/dart_mappable
issue_tracker: https://github.com/schultek/dart_mappable/issues

dependencies:
  analyzer: ^3.1.0
  build: ^2.2.0
  collection: ^1.15.0
  path: ^1.8.0
  source_gen: ^1.2.0
  type_plus: ^0.4.0

dev_dependencies:
  build_runner: ^2.1.0
  lints: ^1.0.1
  test: ^1.20.0

environment:
  sdk: '>=2.12.0 <3.0.0'
