name: dart_mappable
description: Serialize / deserialize dart objects effortlessly, without any boilerplate code or annotations.
version: 0.1.1
repository: https://github.com/schultek/dart_mappable
issue_tracker: https://github.com/schultek/dart_mappable/issues

dependencies:
  analyzer: ^1.4.0
  build: ^2.0.0
  indent: ^1.1.0

dev_dependencies:
  lint: ^1.5.3

environment:
  sdk: '>=2.12.0 <3.0.0'
