name: dart_mappable
description: Serialize / deserialize dart objects effortlessly, without any boilerplate code or compromises.
version: 1.0.0-dev.5
repository: https://github.com/schultek/dart_mappable
issue_tracker: https://github.com/schultek/dart_mappable/issues

dependencies:
  analyzer: ^3.3.1
  build: ^2.2.1
  collection: ^1.16.0
  path: ^1.8.1
  source_gen: ^1.2.1
  type_plus: ^0.6.3

dev_dependencies:
  build_runner: ^2.1.7
  lints: ^1.0.1
  test: ^1.20.1

environment:
  sdk: '>=2.12.0 <3.0.0'
