name: dart_mappable
description: Serialize / deserialize dart objects effortlessly, without any boilerplate code or compromises.
version: 0.6.3
repository: https://github.com/schultek/dart_mappable
issue_tracker: https://github.com/schultek/dart_mappable/issues

dependencies:
  analyzer: ^1.7.0
  build: ^2.0.0
  path: ^1.8.0
  source_gen: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.5
  lint: ^1.5.3
  test: ^1.17.4

environment:
  sdk: '>=2.12.0 <3.0.0'
