builders:
  dart_mappable_builder:
    import: "package:dart_mappable_builder/builder.dart"
    builder_factories: [ "buildMappable" ]
    build_extensions: { ".dart": [ ".mapper.dart" ] }
    required_inputs: [".freezed.dart"]
    auto_apply: dependents
    build_to: source