name: dart_mappable_builder
description: Improved json serialization and data classes with full support for generics, inheritance, customization and more.
version: 2.0.0-dev.2
repository: https://github.com/schultek/dart_mappable
issue_tracker: https://github.com/schultek/dart_mappable/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  analyzer: ^5.0.0
  build: ^2.0.0
  collection: ^1.15.0
  dart_mappable: ^2.0.0-dev.2
  path: ^1.8.0
  source_gen: ^1.2.5

dev_dependencies:
  build_runner: ^2.2.0
  lints: '>=1.0.0 <3.0.0'
