name: dart_mappable_builder
description: Improved json serialization and data classes with full support for generics, inheritance, customization and more.
version: 1.1.3
repository: https://github.com/schultek/dart_mappable
issue_tracker: https://github.com/schultek/dart_mappable/issues

dependencies:
  analyzer: ^3.0.0
  build: ^2.0.0
  collection: ^1.15.0
  dart_mappable: ^1.1.0
  path: ^1.8.0
  source_gen: ^1.2.0

dev_dependencies:
  build_runner: ^2.1.7
  lints: ^1.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'