name: dart_mappable_example

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  dart_mappable: ^1.2.0

dev_dependencies:
  build_runner: ^2.1.0
  dart_mappable_builder: ^1.2.0
  lints: ^2.0.0

dependency_overrides:
  dart_mappable:
    path: ../
  dart_mappable_builder:
    path: ../../dart_mappable_builder