name: dart_mappable_example

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dart_mappable:
    path: ../

dev_dependencies:
  build_runner: ^2.1.0
  dart_mappable_builder:
    path: ../../dart_mappable_builder
  lints: ^1.0.1

dependency_overrides:
  dart_mappable:
    path: ../