name: polymorphic_copywith
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dart_mappable: ^1.1.1

dev_dependencies:
  build_runner: ^2.1.0
  dart_mappable_builder: ^1.1.1
  lints: ^2.0.0

dependency_overrides:
  dart_mappable:
    path: ../../packages/dart_mappable
  dart_mappable_builder:
    path: ../../packages/dart_mappable_builder
