name: json_serializable_compare

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dart_mappable: ^2.0.0
  json_annotation: ^4.7.0
  test: ^1.22.1

dev_dependencies:
  build_runner: ^2.1.0
  dart_mappable_builder: ^2.0.0
  json_serializable: ^6.5.4
  lints: ^2.0.0