name: dart_mappable
description: Improved json serialization and data classes with full support for generics, inheritance, customization and more.
version: 1.1.2
repository: https://github.com/schultek/dart_mappable
issue_tracker: https://github.com/schultek/dart_mappable/issues

dependencies:
  collection: ^1.15.0
  type_plus: ^0.6.3

dev_dependencies:
  build_runner: ^2.1.7
  dart_mappable_builder: ^1.1.0
  lints: ^1.0.1
  test: ^1.20.1

environment:
  sdk: '>=2.12.0 <3.0.0'
