name: dart_mappable
description: Improved json serialization and data classes with full support for generics, inheritance, customization and more.
version: 1.2.0
repository: https://github.com/schultek/dart_mappable
issue_tracker: https://github.com/schultek/dart_mappable/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  type_plus: ^0.6.3

dev_dependencies:
  build_runner: ^2.1.11
  dart_mappable_builder: ^1.2.0
  lints: '>=1.0.0 <3.0.0'
  test: ^1.20.1