name: dart_mappable_example_fic

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dart_mappable: ^1.2.0
  fast_immutable_collections: ^7.4.1

dev_dependencies:
  build_runner: ^2.1.0
  dart_mappable_builder: ^1.1.1
  lints: ^1.0.1

dependency_overrides:
  dart_mappable:
    path: ../../packages/dart_mappable
  dart_mappable_builder:
    path: ../../packages/dart_mappable_builder